import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Hero from "@/components/Hero";

export default function Home() {
	return (
    <>
      <Head>
        <title>WalletConnect | Next Starter Template</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="w-full flex flex-col space-y-4">
        <Hero />
        <div className="px-2">
          <button className="bg-[#6B54EB] w-full text-white py-3 px-3 rounded-md text-[12px]">
            Invite
          </button>
        </div>
		
      </section>
    </>
  );
}
